### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by bigmalsia** [baum1810/protonmail-generator#1]
Exception ignored in: <function Chrome.del at 0x000001D466690F40>
Traceback (most recent call last):
  File "C:\Users\new\Desktop\Lib\site-packages\undetected_chromedriver\__init__.py", line 843, in del
  File "C:\Users\new\Desktop\Lib\site-packages\undetected_chromedriver\__init__.py", line 798, in quit
OSError: [WinError 6] The handle is invalid

Do you know what’s up?

**Comment by bigmalsia** [comment]
I have chrome driver and everything installed. It automatically brings up Google chrome and types protonmails address in the search bar and just before the proton page loads it disconnects?
